# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 07:42
from __future__ import unicode_literals

from .. import models as app_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=app_models.generate_verification_key, max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_keys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
